
# Graphics
SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 900
FULL_SCREEN = False
DRAW_LABELS = False
STEPS_PER_FRAME = 1

# Organisms
NUMBER_OF_ORGANISMS = 20
REPRODUCTION_TIME = 1001
STARTING_ENERGY = 1000
AGE_OF_DEATH = REPRODUCTION_TIME * 3
MAX_ENERGY = STARTING_ENERGY * 2
TIME_TO_NEW_ORGS = 10000

# Brains
NEURAL_LAYERS_PER_BRAIN = 2
NEURONS_PER_LAYER = 10
CONNECTIONS_PER_NEURON = 10

# Map
NUMBER_OF_FOOD_SOURCES = 30
STARTING_FOOD_ENERGY = 10000

# Console
NUMBER_OF_CONSOLE_LINES = 50