
# Graphics
SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 900
FULL_SCREEN = False
DRAW_LABELS = False
STEPS_PER_FRAME = 1

# Organisms
NUMBER_OF_ORGANISMS = 10
REPRODUCTION_TIME = 600
STARTING_ENERGY = 500
AGE_OF_DEATH = REPRODUCTION_TIME * 3
MAX_ENERGY = STARTING_ENERGY * 2

# Map
NUMBER_OF_FOOD_SOURCES = 30
STARTING_FOOD_ENERGY = 10000

# Console
NUMBER_OF_CONSOLE_LINES = 50